### ISSUE TITLE
Badges don't update in GitHub README

### ISSUE THREAD

**Issue by adhirajsinghchauhan** [brackets-extension-badges/badge-provider-nodejs#1]
Badges in my [README](https://github.com/adhirajsinghchauhan/material-theme-brackets):
![badges-noupdate](https://user-images.githubusercontent.com/14949823/27001520-98fca496-4de9-11e7-8292-60525803a250.PNG)

Badges should be:
![badges-update](https://user-images.githubusercontent.com/14949823/27001523-bab114be-4de9-11e7-9865-398e28f28544.PNG)

---
**Possible Fix:** See [this comment](https://github.com/github/markup/issues/224#issuecomment-33454537)

**Comment by bokub** [comment]
So, I have added some headers in a commit [yesterday](https://github.com/brackets-extension-badges/badge-provider-nodejs/commit/c9c1b3c0859497b1a943f3aec95040dacb639da5), but because you have added the badges before the commit, Github might now keep them in cache for some time (I have no idea how long).

You have two solutions:
- Wait for github to refresh the cache, and I hope  the problem will be solved after that
- Change the url of the badges to force a new download, for example add a question mark after the `.svg` in the links, so github will get the new version with the headers.

-----

Cached badge: [![Downloads](https://badges.ml/material-theme-brackets/total.svg)](https://brackets-extension-badges.github.io#material-theme-brackets) 

New badge: [![Downloads](https://badges.ml/material-theme-brackets/total.svg?)](https://brackets-extension-badges.github.io#material-theme-brackets)

I'm not closing the issue right now, I want to wait and see if the new badge gets updated often or not, and how long the cached badge will stay like this.

**Comment by adhirajsinghchauhan** [comment]
@bokub The badges updated after changing the URLs. I'll report back after a few days with an update

**EDIT:** Badges update properly. GitHub revalidates the cache

**Comment by bokub** [comment]
Ok, the badges now update correctly, so I'm closing the issue.

By the way, if you ever need to ask a cache refresh to github, just do the following:
```bash
curl -X PURGE https://camo.githubusercontent.com/123456cachedimageURL789
```
