### ISSUE TITLE
Use m suffix for 1 000 000+ downloads

### ISSUE THREAD

**Issue by Hirse** [brackets-extension-badges/badge-provider-nodejs#2]
The download counter badge uses `k` for thousands, but doesn't handle the case of more than one million downloads very well:
[![Downloads](https://badges.ml/brackets-beautify/total.svg)](https://brackets-extension-badges.github.io#brackets-beautify)

**Comment by bokub** [comment]
Oh, you're totally right! 
I'll check that tomorrow

**Comment by bokub** [comment]
So, the [formatter](https://github.com/brackets-extension-badges/badge-provider-nodejs/blob/master/src/badgeUtils.ts#L66) uses the '_k_' when the number is higher than 10,000 and the '_M_' when it's higher than 10,000,000.
I guess it can make sense, because `1147k ` or `1350` are more significative than `1M` / `1k`, but it's incoherent with other badges services, and a little bit less pretty.

I would like your opinion on this, as you are one of the only two persons with more than 1M downloads

Thanks

**Comment by Hirse** [comment]
For the `1350` case, I agree that it looks nicer than `1k` or `1.3k` (which is also locale-dependent), but `1000k` just looks wrong somehow.

I would maybe go with `113k`, `1.1m`, `11m`. (So decimals, iff it is only one digit, although that is also somewhat inconsistent.)

Do you have formatting examples from other services?

**Comment by bokub** [comment]
Well, [shields.io](http://shields.io/) is the main provider of badges, and they would format it "1M" (no dot), but also "1k"

I guess I'm going to do "1350", "834k" and "1.1M", so that doesn't change anything except for the ones with 1M+ downloads, with enough precision

**Comment by bokub** [comment]
As you can see in the first message of the issue, the problem is now fixed!

:+1:

**Comment by Hirse** [comment]
Great, thank you.
